spring:
  profiles:
    active: dev

logging:
  level:
    jdbc: INFO
    com.thoughtlib.springbatchpractice: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
  file:
    path: /tmp

---

spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://devdb.tixit.co.kr:3306/spring_batch_practice?useUnicode=yes&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: tixit
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 50
      connectionTimeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always
server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /batch
